/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hekai_fftw_android_Utils */

#ifndef _Included_com_hekai_fftw_android_Utils
#define _Included_com_hekai_fftw_android_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftw_init
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftw_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftw_dft_2d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftw_1dft_12d
  (JNIEnv *, jobject);

/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftw_dft_r2c_2d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftw_1dft_1r2c_12d
  (JNIEnv *, jobject);

/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftwf_dft_r2c_2d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftwf_1dft_1r2c_12d
  (JNIEnv *, jobject);

/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftwf_dft_r2c_2d_thread
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftwf_1dft_1r2c_12d_1thread
  (JNIEnv *, jobject);

/*
 * Class:     com_hekai_fftw_android_Utils
 * Method:    fftwf_dft_r2c_2d_thread_measure
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hekai_fftw_1android_Utils_fftwf_1dft_1r2c_12d_1thread_1measure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
